Lab11/Models/CalcModel.cs
namespace Lab1.Models {
    public class CalcModel {
        public readonly int X;
        public readonly int Y;
        public readonly string Sum;
        public readonly string Dif;
        public readonly string Mult;
        public readonly string Div;
        public CalcModel(int x, int y, string sum, string dif, string mult, string div) {
            X = x;
            Y = y;
            Sum = sum;
            Dif = dif;
            Mult = mult;
            Div = div;
        }
    }
}

Lab11/Controllers/CalcServiceController.cs
using Lab1.Models;
using Lab1.Services;
using Microsoft.AspNetCore.Mvc;

namespace Lab1.Controllers
{
    public class CalcServiceController : Controller
    {
        private readonly CalcService _service;

        public CalcServiceController(CalcService service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PassUsingModel()
        {
            return View(_service.GetCalcModel());
        }

        public IActionResult PassUsingViewData()
        {
            var model = _service.GetCalcModel();
            ViewData["X"] = model.X;
            ViewData["Y"] = model.Y;
            ViewData["Sum"] = model.Sum;
            ViewData["Dif"] = model.Dif;
            ViewData["Mult"] = model.Mult;
            ViewData["Div"] = model.Div;
            return View();
        }

        public IActionResult PassUsingViewBag()
        {
            var model = _service.GetCalcModel();
            ViewBag.X = model.X;
            ViewBag.Y = model.Y;
            ViewBag.Sum = model.Sum;
            ViewBag.Dif = model.Dif;
            ViewBag.Mult = model.Mult;
            ViewBag.Div = model.Div;
            return View();
        }

        public IActionResult AccessServiceDirectly()
        {
            return View();
        }
    }
}

Lab11/Views/CalcService/AccessServiceDirectly.cshtml
@using Lab1.Services
@inject CalcService Service
@{
    ViewBag.Title = "AccessServiceDirectly - Backend1";
    var model = Service.GetCalcModel();
}
<h1>AccessServiceDirectly</h1>

<b>Rand value first:</b> @(model.X)<br/>
<b>Rand value second:</b> @(model.Y)<br/>

<b>Add:</b><br />
@(model.Sum)<br />

<b>Dif:</b><br />
@(model.Dif)<br />

<b>Mult:</b><br/>
@(model.Mult)<br />

<b>Div:</b><br/>
@(model.Div)<br />

Lab11/Views/CalcService/Index.cshtml
@{
    ViewBag.Title = "Home Page - Backend1";
}
<h1>Calc Service Demonstration</h1>
<ul>
    <li><a asp-controller="CalcService" asp-action="PassUsingModel">Using Model Calc</a></li>
    <li><a asp-controller="CalcService" asp-action="PassUsingViewData">Using ViewData Calc</a></li>
    <li><a asp-controller="CalcService" asp-action="PassUsingViewBag">Using ViewBag Calc</a></li>
    <li><a asp-controller="CalcService" asp-action="AccessServiceDirectly">Using Service Injection Calc</a></li>
</ul>

Lab11/Views/CalcService/PassUsingModel.cshtml
@model Lab1.Models.CalcModel
@{
    ViewBag.Title = "PassUsingModel - Backend1";
}
<h1>PassUsingModel</h1>
<b>Rand value first:</b> @Model.X<br />
<b>Rand value second:</b> @Model.Y<br />

<b>Add:</b><br />
@Model.Sum<br />

<b>Dif:</b><br />
@Model.Dif<br />

<b>Mult:</b><br />
@Model.Mult<br />

<b>Div:</b><br />
@Model.Div<br />

Lab11/Views/CalcService/PassUsingViewBag.cshtml
@{
    ViewBag.Title = "PassUsingViewBag - Backend1";
}
<h1>PassUsingViewBag</h1>
<b>Rand value first:</b> @ViewBag.X<br/>
<b>Rand value second:</b> @ViewBag.Y<br/>

<b>Add:</b><br/>
@ViewBag.Sum<br/>

<b>Dif:</b><br/>
@ViewBag.Dif<br/>

<b>Mult:</b><br/>
@ViewBag.Mult<br/>

<b>Div:</b><br/>
@ViewBag.Div<br/>

Lab11/Views/CalcService/PassUsingViewData.cshtml
@{
    ViewBag.Title = "PassUsingViewData - Backend1";
}
<h1>PassUsingViewBag</h1>
<b>Rand value first:</b> @ViewData["X"]<br/>
<b>Rand value second:</b> @ViewData["Y"]<br/>

<b>Add:</b><br/>
@ViewData["Sum"]<br/>

<b>Dif:</b><br/>
@ViewData["Dif"]<br/>

<b>Mult:</b><br/>
@ViewData["Mult"]<br/>

<b>Div:</b><br/>
@ViewData["Div"]<br/>

Lab11/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <link rel="stylesheet" href="~/css/main.css" asp-append-version="true"/>
    <title>@ViewBag.Title</title>
</head>
<body>
<header>
    <h2>Backend1</h2>
    <nav><a asp-controller="CalcService" asp-action="Index">Home</a></nav>
</header>
<main>
    @RenderBody()
</main>
<footer>
    <hr/>
    © 2022 - Backend1
</footer>
</body>
</html>